[package]
name = "Fractals"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "29.0.3"
winit = "0.30.13"
pollster = "0.4.0"
wasm-bindgen = "0.2.122"
anyhow = "1.0.102"
wasm-bindgen-futures = "0.4.72"
log = "0.4.30"
env_logger = "0.11.10"
console_log = "1.0.0"
console_error_panic_hook = "0.1.7"
bytemuck = { version = "1.16", features = ["derive"] }